slider_install:
  path: /slider/install
  controller: App\Controller\SliderController::install

slider_auth:
  path: /slider/auth
  controller: App\Controller\SliderController::auth

slider_config:
  path: /slider/config
  controller: App\Controller\SliderController::config

slider_uninstall:
  path: /slider/uninstall
  controller: App\Controller\SliderController::uninstall


js_template_generate:
  path: /slider/lib.js
  controller: App\Controller\SliderController::generateTemplateJs

js_embed_generate:
  path: /slider/embed.js
  controller: App\Controller\SliderController::generateEmbedJs


customer_request:
  path: /customer/request
  controller: App\Controller\CustomerController::customerRequest

customer_erasure:
  path: /customer/erasure
  controller: App\Controller\CustomerController::customerErasure

shop_request:
  path: /shop/request
  controller: App\Controller\CustomerController::shopRequest
