slider_install:
  path: /slider/install
  controller: App\Controller\SliderController::install

slider_auth:
  path: /slider/auth
  controller: App\Controller\SliderController::auth

slider_config:
  path: /slider/config
  controller: App\Controller\SliderController::config

slider_uninstall:
  path: /slider/uninstall
  controller: App\Controller\SliderController::uninstall
