slider_install:
    path: /slider/install
    controller: App\Controller\AppSliderController::install

slider_auth:
  path: /slider/auth
  controller: App\Controller\AppSliderController::auth

slider_config:
  path: /slider/config
  controller: App\Controller\AppSliderConfigController::configRender